repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict
